### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by jitsejan** [jitsejan/jitsejan.com#25]
There is (again) an issue with the Python package versions (markup safe)?

```
02:29:29.564	Initializing build environment. This may take up to a few minutes to complete
02:31:40.903	Success: Finished initializing build environment
02:31:40.903	Cloning repository...
02:32:21.849	Success: Finished cloning repository files
02:32:22.009	Installing dependencies
02:32:22.013	Python version set to 3.7
02:32:23.147	v12.18.0 is already installed.
02:32:23.702	Now using node v12.18.0 (npm v6.14.4)
02:32:23.751	Started restoring cached build plugins
02:32:23.754	Finished restoring cached build plugins
02:32:23.894	Attempting ruby version 2.7.1, read from environment
02:32:25.099	Using ruby version 2.7.1
02:32:25.412	Using PHP version 5.6
02:32:25.412	Installing pip dependencies
02:32:25.413	Started restoring cached pip cache
02:32:25.460	Finished restoring cached pip cache
02:32:26.053	Collecting docutils
02:32:26.267	  Downloading docutils-0.18.1-py2.py3-none-any.whl (570 kB)
02:32:26.514	Collecting feedgenerator
02:32:26.521	  Downloading feedgenerator-2.0.0-py3-none-any.whl (21 kB)
02:32:26.642	Collecting importlib-metadata
02:32:26.647	  Downloading importlib_metadata-4.11.1-py3-none-any.whl (17 kB)
02:32:26.738	Collecting invoke
02:32:26.755	  Downloading invoke-1.6.0-py3-none-any.whl (212 kB)
02:32:26.827	Collecting Jinja2==2.11.3
02:32:26.837	  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
02:32:26.899	Collecting Markdown
02:32:26.904	  Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)
02:32:26.978	Collecting nbconvert==5.6.0
02:32:26.986	  Downloading nbconvert-5.6.0-py2.py3-none-any.whl (453 kB)
02:32:27.153	Collecting notebook==5.6.0
02:32:27.168	  Downloading notebook-5.6.0-py2.py3-none-any.whl (8.9 MB)
02:32:28.039	Collecting pelican
02:32:28.050	  Downloading pelican-4.7.2-py3-none-any.whl (1.4 MB)
02:32:28.276	Collecting Pygments
02:32:28.292	  Downloading Pygments-2.11.2-py3-none-any.whl (1.1 MB)
02:32:28.435	Collecting python-dateutil
02:32:28.441	  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
02:32:28.611	Collecting pytz
02:32:28.618	  Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
02:32:28.777	Collecting six
02:32:28.782	  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
02:32:28.817	Collecting typing-extensions
02:32:28.828	  Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)
02:32:28.861	Collecting Unidecode
02:32:28.869	  Downloading Unidecode-1.3.2-py3-none-any.whl (235 kB)
02:32:28.968	Collecting zipp
02:32:28.979	  Downloading zipp-3.7.0-py3-none-any.whl (5.3 kB)
02:32:29.012	Collecting jupyter==1.0.0
02:32:29.021	  Downloading jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
02:32:29.080	Collecting jupyter-client==6.1.12
02:32:29.089	  Downloading jupyter_client-6.1.12-py3-none-any.whl (112 kB)
02:32:29.172	Collecting jupyter-console==6.4.0
02:32:29.179	  Downloading jupyter_console-6.4.0-py3-none-any.whl (22 kB)
02:32:29.229	Collecting jupyter-core==4.7.1
02:32:29.237	  Downloading jupyter_core-4.7.1-py3-none-any.whl (82 kB)
02:32:29.271	Collecting jupyterlab-pygments==0.1.2
02:32:29.277	  Downloading jupyterlab_pygments-0.1.2-py2.py3-none-any.whl (4.6 kB)
02:32:29.321	Collecting jupyterlab-widgets==1.0.0
02:32:29.327	  Downloading jupyterlab_widgets-1.0.0-py3-none-any.whl (243 kB)
02:32:29.447	Collecting pelican_jupyter==0.10.0
02:32:29.495	  Downloading pelican-jupyter-0.10.0.tar.gz (122 kB)
02:32:29.520	  Installing build dependencies: started
02:32:31.872	  Installing build dependencies: finished with status 'done'
02:32:31.876	  Getting requirements to build wheel: started
02:32:32.120	  Getting requirements to build wheel: finished with status 'done'
02:32:32.126	    Preparing wheel metadata: started
02:32:33.261	    Preparing wheel metadata: finished with status 'done'
02:32:33.300	Collecting bs4==0.0.1
02:32:33.306	  Downloading bs4-0.0.1.tar.gz (1.1 kB)
02:32:33.637	Collecting webassets==2.0
02:32:33.645	  Downloading webassets-2.0-py3-none-any.whl (142 kB)
02:32:33.753	Collecting lessc==0.1.3
02:32:33.778	  Downloading lessc-0.1.3.tar.gz (8.3 kB)
02:32:34.290	Collecting MarkupSafe>=0.23
02:32:34.305	  Downloading MarkupSafe-2.1.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
02:32:34.339	Collecting testpath
02:32:34.345	  Downloading testpath-0.5.0-py3-none-any.whl (84 kB)
02:32:34.394	Collecting nbformat>=4.4
02:32:34.400	  Downloading nbformat-5.1.3-py3-none-any.whl (178 kB)
02:32:34.483	Collecting mistune<2,>=0.8.1
02:32:34.493	  Downloading mistune-0.8.4-py2.py3-none-any.whl (16 kB)
02:32:34.540	Collecting pandocfilters>=1.4.1
02:32:34.549	  Downloading pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
02:32:34.597	Collecting entrypoints>=0.2.2
02:32:34.612	  Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
02:32:34.689	Collecting bleach
02:32:34.701	  Downloading bleach-4.1.0-py2.py3-none-any.whl (157 kB)
02:32:34.774	Collecting traitlets>=4.2
02:32:34.785	  Downloading traitlets-5.1.1-py3-none-any.whl (102 kB)
02:32:34.831	Collecting defusedxml
02:32:34.839	  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
02:32:34.945	Collecting ipykernel
02:32:34.955	  Downloading ipykernel-6.9.1-py3-none-any.whl (128 kB)
02:32:35.013	Collecting ipython-genutils
02:32:35.021	  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
02:32:35.063	Collecting Send2Trash
02:32:35.226	  Downloading Send2Trash-1.8.0-py3-none-any.whl (18 kB)
02:32:35.548	Collecting pyzmq>=17
02:32:35.564	  Downloading pyzmq-22.3.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.1 MB)
02:32:35.684	Collecting prometheus-client
02:32:35.690	  Downloading prometheus_client-0.13.1-py3-none-any.whl (57 kB)
02:32:35.743	Collecting terminado>=0.8.1
02:32:35.749	  Downloading terminado-0.13.1-py3-none-any.whl (14 kB)
02:32:35.862	Collecting tornado>=4
02:32:35.871	  Downloading tornado-6.1-cp37-cp37m-manylinux2010_x86_64.whl (428 kB)
02:32:36.039	Collecting rich>=10.1
02:32:36.045	  Downloading rich-11.2.0-py3-none-any.whl (217 kB)
02:32:36.104	Collecting blinker>=1.4
02:32:36.122	  Downloading blinker-1.4.tar.gz (111 kB)
02:32:36.550	Collecting ipywidgets
02:32:36.557	  Downloading ipywidgets-7.6.5-py2.py3-none-any.whl (121 kB)
02:32:36.650	Collecting qtconsole
02:32:36.656	  Downloading qtconsole-5.2.2-py3-none-any.whl (120 kB)
02:32:36.812	Collecting ipython
02:32:36.818	  Downloading ipython-7.31.1-py3-none-any.whl (792 kB)
02:32:37.099	Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
02:32:37.105	  Downloading prompt_toolkit-3.0.28-py3-none-any.whl (380 kB)
02:32:37.193	Collecting beautifulsoup4
02:32:37.200	  Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
02:32:37.234	Collecting asset>=0.6.12
02:32:37.240	  Downloading asset-0.6.13.tar.gz (28 kB)
02:32:37.626	Collecting jsonschema!=2.5.0,>=2.4
02:32:37.631	  Downloading jsonschema-4.4.0-py3-none-any.whl (72 kB)
02:32:37.725	Collecting packaging
02:32:37.728	  Using cached packaging-21.3-py3-none-any.whl (40 kB)
02:32:37.754	Collecting webencodings
02:32:37.758	  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
02:32:37.805	Collecting nest-asyncio
02:32:37.811	  Downloading nest_asyncio-1.5.4-py3-none-any.whl (5.1 kB)
02:32:37.834	Collecting matplotlib-inline<0.2.0,>=0.1.0
02:32:37.839	  Downloading matplotlib_inline-0.1.3-py3-none-any.whl (8.2 kB)
02:32:38.152	Collecting debugpy<2.0,>=1.0.0
02:32:38.163	  Downloading debugpy-1.5.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.9 MB)
02:32:38.341	Collecting ptyprocess; os_name != "nt"
02:32:38.346	  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
02:32:38.377	Collecting commonmark<0.10.0,>=0.9.0
02:32:38.383	  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
02:32:38.431	Collecting colorama<0.5.0,>=0.4.0
02:32:38.435	  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
02:32:38.509	Collecting widgetsnbextension~=3.5.0
02:32:38.517	  Downloading widgetsnbextension-3.5.2-py2.py3-none-any.whl (1.6 MB)
02:32:38.647	Collecting qtpy
02:32:38.653	  Downloading QtPy-2.0.1-py3-none-any.whl (65 kB)
02:32:38.719	Collecting jedi>=0.16
02:32:38.735	  Downloading jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
02:32:39.152	Collecting backcall
02:32:39.157	  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
02:32:39.186	Collecting pexpect>4.3; sys_platform != "win32"
02:32:39.191	  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
02:32:39.207	Requirement already satisfied: setuptools>=18.5 in /opt/buildhome/python3.7/lib/python3.7/site-packages (from ipython->jupyter-console==6.4.0->-r requirements.txt (line 19)) (49.2.0)
02:32:39.265	Collecting decorator
02:32:39.280	  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
02:32:39.309	Collecting pickleshare
02:32:39.320	  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
02:32:39.358	Collecting wcwidth
02:32:39.363	  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
02:32:39.420	Collecting soupsieve>1.2
02:32:39.425	  Downloading soupsieve-2.3.1-py3-none-any.whl (37 kB)
02:32:39.452	Collecting globre>=0.1.5
02:32:39.462	  Downloading globre-0.1.5.tar.gz (20 kB)
02:32:39.787	Collecting aadict>=0.2.2
02:32:39.814	  Downloading aadict-0.2.3.tar.gz (16 kB)
02:32:40.164	Collecting attrs>=17.4.0
02:32:40.169	  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
02:32:40.286	Collecting importlib-resources>=1.4.0; python_version < "3.9"
02:32:40.291	  Downloading importlib_resources-5.4.0-py3-none-any.whl (28 kB)
02:32:40.394	Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
02:32:40.399	  Downloading pyrsistent-0.18.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (117 kB)
02:32:40.525	Collecting pyparsing!=3.0.5,>=2.0.2
02:32:40.528	  Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
02:32:40.572	Collecting parso<0.9.0,>=0.8.0
02:32:40.578	  Downloading parso-0.8.3-py2.py3-none-any.whl (100 kB)
02:32:40.602	Building wheels for collected packages: pelican-jupyter, bs4, lessc, blinker, asset, globre, aadict
02:32:40.604	  Building wheel for pelican-jupyter (PEP 517): started
02:32:41.939	  Building wheel for pelican-jupyter (PEP 517): finished with status 'done'
02:32:41.941	  Created wheel for pelican-jupyter: filename=pelican_jupyter-0.10.0-py2.py3-none-any.whl size=118824 sha256=c701ac3e15dd490b299f77b986b19725884dd0eba65b9fd35aba2f19ee50e287
02:32:41.942	  Stored in directory: /opt/buildhome/.cache/pip/wheels/ae/59/1a/15135ad7b7cf1b486c357e19b62f39975aea393f5de0be2d7c
02:32:41.943	  Building wheel for bs4 (setup.py): started
02:32:42.221	  Building wheel for bs4 (setup.py): finished with status 'done'
02:32:42.222	  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1272 sha256=7ebdae2d91fbb485abf9e5475071db35b934f8b49d7069904e04ebca47076706
02:32:42.222	  Stored in directory: /opt/buildhome/.cache/pip/wheels/0a/9e/ba/20e5bbc1afef3a491f0b3bb74d508f99403aabe76eda2167ca
02:32:42.224	  Building wheel for lessc (setup.py): started
02:32:42.578	  Building wheel for lessc (setup.py): finished with status 'done'
02:32:42.579	  Created wheel for lessc: filename=lessc-0.1.3-py3-none-any.whl size=9381 sha256=21f2e2fc3d5bdfbe06df56c61f556e1185f26369cb1de0a06d56b0de987ace83
02:32:42.579	  Stored in directory: /opt/buildhome/.cache/pip/wheels/48/ad/a0/3ec266d366eba4d52a882e761f573b17c6f65644130da2b44b
02:32:42.580	  Building wheel for blinker (setup.py): started
02:32:42.929	  Building wheel for blinker (setup.py): finished with status 'done'
02:32:42.930	  Created wheel for blinker: filename=blinker-1.4-py3-none-any.whl size=13452 sha256=8f77b9ef898e723de841270a07a3aa5f09bbcda143002d6f53ce595e8021ecc5
02:32:42.930	  Stored in directory: /opt/buildhome/.cache/pip/wheels/22/f5/18/df711b66eb25b21325c132757d4314db9ac5e8dabeaf196eab
02:32:42.932	  Building wheel for asset (setup.py): started
02:32:43.290	  Building wheel for asset (setup.py): finished with status 'done'
02:32:43.291	  Created wheel for asset: filename=asset-0.6.13-py3-none-any.whl size=30689 sha256=7b167335c51be1546a8803e101a3dc7d39939b69080da793e56b3b8762cf7e13
02:32:43.291	  Stored in directory: /opt/buildhome/.cache/pip/wheels/da/1d/ad/e736c3922574b75669c23fb0748f9877ecbd019f9cfaeb983d
02:32:43.293	  Building wheel for globre (setup.py): started
02:32:43.632	  Building wheel for globre (setup.py): finished with status 'done'
02:32:43.633	  Created wheel for globre: filename=globre-0.1.5-py3-none-any.whl size=19526 sha256=ae31516e979e28a57e0ab8f92bf4e6e246c2d62bbc098ba09e6573f5ac3b0e47
02:32:43.633	  Stored in directory: /opt/buildhome/.cache/pip/wheels/40/95/37/5303ce04fce53b6e64ed74a3f0a0e9ea11c348cac0c5c42a76
02:32:43.636	  Building wheel for aadict (setup.py): started
02:32:43.978	  Building wheel for aadict (setup.py): finished with status 'done'
02:32:43.979	  Created wheel for aadict: filename=aadict-0.2.3-py3-none-any.whl size=16557 sha256=8d8321dd780627baeaa068d08e04cc49705ede79106626edf5ab27968fd1eeac
02:32:43.979	  Stored in directory: /opt/buildhome/.cache/pip/wheels/83/77/ad/7c7ef95a7089fbf69d15b0e7bb92c9c05fb363ea4cd8c7556b
02:32:43.980	Successfully built pelican-jupyter bs4 lessc blinker asset globre aadict
02:32:44.501	Installing collected packages: docutils, pytz, feedgenerator, typing-extensions, zipp, importlib-metadata, invoke, MarkupSafe, Jinja2, Markdown, testpath, traitlets, jupyter-core, ipython-genutils, attrs, importlib-resources, pyrsistent, jsonschema, nbformat, mistune, Pygments, pandocfilters, entrypoints, six, pyparsing, packaging, webencodings, bleach, defusedxml, nbconvert, nest-asyncio, tornado, matplotlib-inline, parso, jedi, backcall, ptyprocess, pexpect, wcwidth, prompt-toolkit, decorator, pickleshare, ipython, python-dateutil, pyzmq, jupyter-client, debugpy, ipykernel, Send2Trash, prometheus-client, terminado, notebook, commonmark, colorama, rich, blinker, Unidecode, pelican, jupyterlab-widgets, widgetsnbextension, ipywidgets, jupyter-console, qtpy, qtconsole, jupyter, jupyterlab-pygments, pelican-jupyter, soupsieve, beautifulsoup4, bs4, webassets, globre, aadict, asset, lessc
02:32:54.391	Successfully installed Jinja2-2.11.3 Markdown-3.3.6 MarkupSafe-2.1.0 Pygments-2.11.2 Send2Trash-1.8.0 Unidecode-1.3.2 aadict-0.2.3 asset-0.6.13 attrs-21.4.0 backcall-0.2.0 beautifulsoup4-4.10.0 bleach-4.1.0 blinker-1.4 bs4-0.0.1 colorama-0.4.4 commonmark-0.9.1 debugpy-1.5.1 decorator-5.1.1 defusedxml-0.7.1 docutils-0.18.1 entrypoints-0.4 feedgenerator-2.0.0 globre-0.1.5 importlib-metadata-4.11.1 importlib-resources-5.4.0 invoke-1.6.0 ipykernel-6.9.1 ipython-7.31.1 ipython-genutils-0.2.0 ipywidgets-7.6.5 jedi-0.18.1 jsonschema-4.4.0 jupyter-1.0.0 jupyter-client-6.1.12 jupyter-console-6.4.0 jupyter-core-4.7.1 jupyterlab-pygments-0.1.2 jupyterlab-widgets-1.0.0 lessc-0.1.3 matplotlib-inline-0.1.3 mistune-0.8.4 nbconvert-5.6.0 nbformat-5.1.3 nest-asyncio-1.5.4 notebook-5.6.0 packaging-21.3 pandocfilters-1.5.0 parso-0.8.3 pelican-4.7.2 pelican-jupyter-0.10.0 pexpect-4.8.0 pickleshare-0.7.5 prometheus-client-0.13.1 prompt-toolkit-3.0.28 ptyprocess-0.7.0 pyparsing-3.0.7 pyrsistent-0.18.1 python-dateutil-2.8.2 pytz-2021.3 pyzmq-22.3.0 qtconsole-5.2.2 qtpy-2.0.1 rich-11.2.0 six-1.16.0 soupsieve-2.3.1 terminado-0.13.1 testpath-0.5.0 tornado-6.1 traitlets-5.1.1 typing-extensions-4.1.1 wcwidth-0.2.5 webassets-2.0 webencodings-0.5.1 widgetsnbextension-3.5.2 zipp-3.7.0
02:32:54.417	WARNING: You are using pip version 20.2b1; however, version 22.0.3 is available.
02:32:54.418	You should consider upgrading via the '/opt/buildhome/python3.7/bin/python3.7 -m pip install --upgrade pip' command.
02:32:54.753	Pip dependencies installed
02:32:54.799	5.2 is already installed.
02:32:54.806	Using Swift version 5.2
02:32:54.806	Installing Hugo 0.54.0
02:32:55.611	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
02:32:55.613	Started restoring cached go cache
02:32:55.617	Finished restoring cached go cache
02:32:55.649	go version go1.14.4 linux/amd64
02:32:55.655	go version go1.14.4 linux/amd64
02:32:55.657	Installing missing commands
02:32:55.657	Verify run directory
02:32:55.657	Executing user command: make html
02:32:55.663	"pelican" "/opt/buildhome/repo/content" -o "/opt/buildhome/repo/output" -s "/opt/buildhome/repo/pelicanconf.py" 
02:32:55.825	Traceback (most recent call last):
02:32:55.825	  File "/opt/buildhome/python3.7/bin/pelican", line 5, in <module>
02:32:55.825	    from pelican.__main__ import main
02:32:55.825	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/pelican/__init__.py", line 21, in <module>
02:32:55.825	    from pelican.generators import (ArticlesGenerator,  # noqa: I100
02:32:55.825	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/pelican/generators.py", line 11, in <module>
02:32:55.827	    from jinja2 import (BaseLoader, ChoiceLoader, Environment, FileSystemLoader,
02:32:55.828	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
02:32:55.828	    from .environment import Environment
02:32:55.828	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
02:32:55.828	    from .defaults import BLOCK_END_STRING
02:32:55.828	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
02:32:55.828	    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
02:32:55.828	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
02:32:55.828	    from markupsafe import soft_unicode
02:32:55.828	ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/buildhome/python3.7/lib/python3.7/site-packages/markupsafe/__init__.py)
02:32:55.845	Makefile:51: recipe for target 'html' failed
02:32:55.845	make: *** [html] Error 1
02:32:55.847	Failed: build command exited with code: 2

```

**Comment by jitsejan** [comment]
Known issue here https://github.com/pallets/markupsafe/issues/286.

Fix version for Markupsafe to 2.0.1 for now.
